trigger:
- main

pool:
 vmImage: windows-latest

steps:
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    action: 'Create Or Update Resource Group'
    azureResourceManagerConnection: 'Mentorship(df95927c-f1ac-4464-84ac-f8982407cd53)'
    subscriptionId: 'df95927c-f1ac-4464-84ac-f8982407cd53'
    location: 'East US'
    templateLocation: 'Linked artifact'
    csmFile: 'iac/load-balancer/arm/template.json'
    csmParametersFile: 'iac/load-balancer/arm/parameters.json'
    deploymentMode: 'Incremental'